In [1]:
# https://www.kaggle.com/burhanykiyakoglu/predicting-house-prices

import numpy as np
import pandas as pd
import seaborn as sns
sns.set_context("paper")   

import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')

import warnings
warnings.simplefilter('ignore')


import statistics
import math
from random import random
import time

from IPython.display import display
from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')


#Common Model Algorithms
from sklearn.linear_model import Lasso, ElasticNet, ElasticNetCV
from sklearn.ensemble import GradientBoostingRegressor, IsolationForest, AdaBoostRegressor
from sklearn.linear_model import ElasticNetCV, LassoCV, RidgeCV
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import mean_squared_error
from mlxtend.regressor import StackingCVRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
import matplotlib.pyplot as plt
import scipy.stats as stats
import sklearn.linear_model as linear_model
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

#Common Model Helpers
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn import feature_selection
from sklearn import model_selection
from sklearn import metrics

ModuleNotFoundError: No module named 'mlxtend'

In [2]:
d_train_x = pd.read_csv('dev_rsc/d_train_x.csv',index_col=0)
d_train_y = pd.read_csv('dev_rsc/d_train_y.csv',index_col=0)
d_test_x = pd.read_csv('dev_rsc/d_test_x.csv',index_col=0)

print(d_train_x.shape)
print(d_train_y.shape)
print(d_test_x.shape)

(1452, 350)
(1452, 1)
(1459, 350)

In [3]:
def prtSep(length=20, marker="-"):
    print( marker * length)
    
def RMSE_log(true,pred):
    RMSE = metrics.mean_squared_error(np.log(true),np.log(pred))**0.5
    return RMSE

In [10]:
d_train_y

      SalePrice
0     12.247699
1     12.109016
2     12.317171
3     11.849405
4     12.429220
...         ...
1455  12.072547
1456  12.254868
1457  12.493133
1458  11.864469
1459  11.901590

[1452 rows x 1 columns]

In [8]:
print(d_train_x.shape)
print(d_train_y.shape)

df_concat = pd.concat([d_train_x, d_train_y], axis=1)
print(df_concat.shape)

(1452, 350)
(1452, 1)
(1460, 351)

In [14]:
df_concat[df_concat["1stFlrSF"].isnull()]

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,EnclosedPorch,...,Street_Pave,Utilities_AllPub,Utilities_NoSeWa,Utilities_None,YrSold_2006,YrSold_2007,YrSold_2008,YrSold_2009,YrSold_2010,SalePrice
1452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.884496
1453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.344519
1454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.128117
1455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.072547
1456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.254868
1457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.493133
1458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.864469
1459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.901590

In [18]:
train_data_dm,test_data_dm = train_test_split(df_dm,train_size = 0.8,random_state=3)

features = ['bedrooms','bathrooms','sqft_living','sqft_lot','floors','zipcode']
complex_model_1 = linear_model.LinearRegression()
complex_model_1.fit(train_data_dm[features],train_data_dm['price'])

print('Intercept: {}'.format(complex_model_1.intercept_))
print('Coefficients: {}'.format(complex_model_1.coef_))

pred = complex_model_1.predict(test_data_dm[features])
rmsecm = float(format(np.sqrt(metrics.mean_squared_error(test_data_dm['price'],pred)),'.3f'))
rtrcm = float(format(complex_model_1.score(train_data_dm[features],train_data_dm['price']),'.3f'))
artrcm = float(format(adjustedR2(complex_model_1.score(train_data_dm[features],train_data_dm['price']),train_data_dm.shape[0],len(features)),'.3f'))
rtecm = float(format(complex_model_1.score(test_data_dm[features],test_data_dm['price']),'.3f'))
artecm = float(format(adjustedR2(complex_model_1.score(test_data_dm[features],test_data['price']),test_data_dm.shape[0],len(features)),'.3f'))
cv = float(format(cross_val_score(complex_model_1,df_dm[features],df_dm['price'],cv=5).mean(),'.3f'))

r = evaluation.shape[0]
evaluation.loc[r] = ['Multiple Regression-1','selected features',rmsecm,rtrcm,artrcm,rtecm,artecm,cv]
evaluation.sort_values(by = '5-Fold Cross Validation', ascending=False)

NameError: name 'y_test' is not defined

In [13]:
import sklearn
sklearn.__version__

'0.22.1'